#!/bin/bash
# One-command setup for bllvm-bench
# Clones dependencies automatically if not found

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Check if we should auto-clone (non-interactive)
AUTO_CLONE="${BLLVM_BENCH_AUTO_SETUP:-0}"

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  bllvm-bench: Quick Setup                                      ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""

# Source path discovery
eval "$(bash scripts/discover-paths.sh 2>/dev/null || true)"

CLONE_DIR="${BLLVM_BENCH_CLONE_DIR:-$SCRIPT_DIR/../dependencies}"
mkdir -p "$CLONE_DIR"

# Check and clone Bitcoin Core
if [ -z "$CORE_PATH" ] || [ ! -d "$CORE_PATH" ]; then
    CORE_CLONE_DIR="$CLONE_DIR/bitcoin"
    if [ -d "$CORE_CLONE_DIR" ]; then
        echo "✅ Using existing Bitcoin Core: $CORE_CLONE_DIR"
        CORE_PATH="$CORE_CLONE_DIR"
    else
        if [ "$AUTO_CLONE" = "1" ]; then
            echo "📦 Cloning Bitcoin Core..."
            git clone --depth 1 https://github.com/bitcoin/bitcoin.git "$CORE_CLONE_DIR" || {
                echo "⚠️  Failed to clone Bitcoin Core (will skip Core benchmarks)"
                CORE_PATH=""
            }
            if [ -d "$CORE_CLONE_DIR" ]; then
                CORE_PATH="$CORE_CLONE_DIR"
                echo "✅ Bitcoin Core cloned"
            fi
        else
            echo "⚠️  Bitcoin Core not found (Core benchmarks will be skipped)"
            echo "   To clone: git clone https://github.com/bitcoin/bitcoin.git $CORE_CLONE_DIR"
            CORE_PATH=""
        fi
    fi
else
    echo "✅ Bitcoin Core found: $CORE_PATH"
fi

# Check and clone bllvm-consensus
if [ -z "$COMMONS_CONSENSUS_PATH" ] || [ ! -d "$COMMONS_CONSENSUS_PATH" ]; then
    CONSENSUS_CLONE_DIR="$CLONE_DIR/bllvm-consensus"
    if [ -d "$CONSENSUS_CLONE_DIR" ]; then
        echo "✅ Using existing bllvm-consensus: $CONSENSUS_CLONE_DIR"
        COMMONS_CONSENSUS_PATH="$CONSENSUS_CLONE_DIR"
    else
        if [ "$AUTO_CLONE" = "1" ]; then
            echo "📦 Cloning bllvm-consensus..."
            git clone https://github.com/BTCDecoded/bllvm-consensus.git "$CONSENSUS_CLONE_DIR" || {
                echo "⚠️  Failed to clone bllvm-consensus"
                COMMONS_CONSENSUS_PATH=""
            }
            if [ -d "$CONSENSUS_CLONE_DIR" ]; then
                COMMONS_CONSENSUS_PATH="$CONSENSUS_CLONE_DIR"
                echo "✅ bllvm-consensus cloned"
            fi
        else
            echo "⚠️  bllvm-consensus not found (Commons benchmarks will be skipped)"
            echo "   To clone: git clone https://github.com/BTCDecoded/bllvm-consensus.git $CONSENSUS_CLONE_DIR"
            COMMONS_CONSENSUS_PATH=""
        fi
    fi
else
    echo "✅ bllvm-consensus found: $COMMONS_CONSENSUS_PATH"
fi

# Check and clone bllvm-node
if [ -z "$COMMONS_NODE_PATH" ] || [ ! -d "$COMMONS_NODE_PATH" ]; then
    NODE_CLONE_DIR="$CLONE_DIR/bllvm-node"
    if [ -d "$NODE_CLONE_DIR" ]; then
        echo "✅ Using existing bllvm-node: $NODE_CLONE_DIR"
        COMMONS_NODE_PATH="$NODE_CLONE_DIR"
    else
        if [ "$AUTO_CLONE" = "1" ]; then
            echo "📦 Cloning bllvm-node..."
            git clone https://github.com/BTCDecoded/bllvm-node.git "$NODE_CLONE_DIR" || {
                echo "⚠️  Failed to clone bllvm-node"
                COMMONS_NODE_PATH=""
            }
            if [ -d "$NODE_CLONE_DIR" ]; then
                COMMONS_NODE_PATH="$NODE_CLONE_DIR"
                echo "✅ bllvm-node cloned"
            fi
        else
            echo "⚠️  bllvm-node not found (some Commons benchmarks may be unavailable)"
            echo "   To clone: git clone https://github.com/BTCDecoded/bllvm-node.git $NODE_CLONE_DIR"
            COMMONS_NODE_PATH=""
        fi
    fi
else
    echo "✅ bllvm-node found: $COMMONS_NODE_PATH"
fi

# Save config
CONFIG_FILE="$SCRIPT_DIR/config/config.toml"
mkdir -p "$(dirname "$CONFIG_FILE")"

cat > "$CONFIG_FILE" << EOF
# bllvm-bench Configuration
# Auto-generated by setup.sh

[paths]
core_path = "${CORE_PATH:-}"
commons_consensus_path = "${COMMONS_CONSENSUS_PATH:-}"
commons_node_path = "${COMMONS_NODE_PATH:-}"
results_dir = "./results"

[benchmarks]
default_suite = "fair"
default_timeout = 300

[report]
generate_html = true
generate_json = true
output_dir = "./results"
EOF

echo ""
echo "✅ Setup complete! Configuration saved to: $CONFIG_FILE"
echo ""
echo "Next steps:"
if [ -n "$CORE_PATH" ] && [ ! -f "$CORE_PATH/build/bin/bench_bitcoin" ]; then
    echo "  1. Build Bitcoin Core:"
    echo "     cd $CORE_PATH && ./autogen.sh && ./configure && make bench_bitcoin"
    echo ""
fi
echo "  2. Run benchmarks:"
echo "     make bench"
echo "     # or: ./run-benchmarks.sh fair"
echo ""

