#!/bin/bash
# Setup Dependencies for bllvm-bench
# Optionally clones Bitcoin Core and Bitcoin Commons if not found

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BLLVM_BENCH_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Source path discovery
eval "$(bash "$BLLVM_BENCH_ROOT/scripts/discover-paths.sh")"

# Default clone location (can be overridden)
CLONE_DIR="${BLLVM_BENCH_CLONE_DIR:-$BLLVM_BENCH_ROOT/../dependencies}"
mkdir -p "$CLONE_DIR"

echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  bllvm-bench: Dependency Setup                                 ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "Checking for dependencies..."
echo ""

# Check Bitcoin Core
if [ -z "$CORE_PATH" ] || [ ! -d "$CORE_PATH" ]; then
    echo "❌ Bitcoin Core not found"
    read -p "Clone Bitcoin Core? (y/N): " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        CORE_CLONE_DIR="$CLONE_DIR/bitcoin"
        if [ -d "$CORE_CLONE_DIR" ]; then
            echo "⚠️  Directory exists: $CORE_CLONE_DIR"
            read -p "Use existing? (Y/n): " -n 1 -r
            echo
            if [[ ! $REPLY =~ ^[Nn]$ ]]; then
                CORE_PATH="$CORE_CLONE_DIR"
            fi
        else
            echo "Cloning Bitcoin Core to $CORE_CLONE_DIR..."
            git clone https://github.com/bitcoin/bitcoin.git "$CORE_CLONE_DIR" || {
                echo "❌ Failed to clone Bitcoin Core"
                exit 1
            }
            CORE_PATH="$CORE_CLONE_DIR"
            echo "✅ Bitcoin Core cloned"
            echo ""
            echo "⚠️  You need to build Core with:"
            echo "   cd $CORE_PATH"
            echo "   ./autogen.sh"
            echo "   ./configure"
            echo "   make bench_bitcoin"
        fi
    else
        echo "Skipping Bitcoin Core (Core benchmarks will be unavailable)"
    fi
else
    echo "✅ Bitcoin Core found: $CORE_PATH"
fi

echo ""

# Check Bitcoin Commons (bllvm-consensus)
if [ -z "$COMMONS_CONSENSUS_PATH" ] || [ ! -d "$COMMONS_CONSENSUS_PATH" ]; then
    echo "❌ Bitcoin Commons (bllvm-consensus) not found"
    read -p "Clone bllvm-consensus? (y/N): " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        CONSENSUS_CLONE_DIR="$CLONE_DIR/bllvm-consensus"
        if [ -d "$CONSENSUS_CLONE_DIR" ]; then
            echo "⚠️  Directory exists: $CONSENSUS_CLONE_DIR"
            read -p "Use existing? (Y/n): " -n 1 -r
            echo
            if [[ ! $REPLY =~ ^[Nn]$ ]]; then
                COMMONS_CONSENSUS_PATH="$CONSENSUS_CLONE_DIR"
            fi
        else
            echo "Cloning bllvm-consensus to $CONSENSUS_CLONE_DIR..."
            git clone https://github.com/BTCDecoded/bllvm-consensus.git "$CONSENSUS_CLONE_DIR" || {
                echo "❌ Failed to clone bllvm-consensus"
                exit 1
            }
            COMMONS_CONSENSUS_PATH="$CONSENSUS_CLONE_DIR"
            echo "✅ bllvm-consensus cloned"
        fi
    else
        echo "Skipping bllvm-consensus (Commons benchmarks will be unavailable)"
    fi
else
    echo "✅ bllvm-consensus found: $COMMONS_CONSENSUS_PATH"
fi

echo ""

# Check Bitcoin Commons (bllvm-node)
if [ -z "$COMMONS_NODE_PATH" ] || [ ! -d "$COMMONS_NODE_PATH" ]; then
    echo "❌ Bitcoin Commons (bllvm-node) not found"
    read -p "Clone bllvm-node? (y/N): " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        NODE_CLONE_DIR="$CLONE_DIR/bllvm-node"
        if [ -d "$NODE_CLONE_DIR" ]; then
            echo "⚠️  Directory exists: $NODE_CLONE_DIR"
            read -p "Use existing? (Y/n): " -n 1 -r
            echo
            if [[ ! $REPLY =~ ^[Nn]$ ]]; then
                COMMONS_NODE_PATH="$NODE_CLONE_DIR"
            fi
        else
            echo "Cloning bllvm-node to $NODE_CLONE_DIR..."
            git clone https://github.com/BTCDecoded/bllvm-node.git "$NODE_CLONE_DIR" || {
                echo "❌ Failed to clone bllvm-node"
                exit 1
            }
            COMMONS_NODE_PATH="$NODE_CLONE_DIR"
            echo "✅ bllvm-node cloned"
        fi
    else
        echo "Skipping bllvm-node (some Commons benchmarks may be unavailable)"
    fi
else
    echo "✅ bllvm-node found: $COMMONS_NODE_PATH"
fi

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  Setup Complete                                                ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""

# Update config file with discovered/cloned paths
CONFIG_FILE="$BLLVM_BENCH_ROOT/config/config.toml"
mkdir -p "$(dirname "$CONFIG_FILE")"

cat > "$CONFIG_FILE" << EOF
# bllvm-bench Configuration
# Auto-generated by setup-dependencies.sh

[paths]
# Bitcoin Core path
core_path = "${CORE_PATH:-}"

# Bitcoin Commons paths
commons_consensus_path = "${COMMONS_CONSENSUS_PATH:-}"
commons_node_path = "${COMMONS_NODE_PATH:-}"

# Results directory
results_dir = "./results"

[benchmarks]
# Which benchmarks to run by default
default_suite = "fair"

# Timeout for benchmarks (seconds)
default_timeout = 300

[report]
# Report generation options
generate_html = true
generate_json = true
output_dir = "./results"
EOF

echo "Configuration saved to: $CONFIG_FILE"
echo ""
echo "Next steps:"
if [ -n "$CORE_PATH" ] && [ ! -f "$CORE_PATH/build/bin/bench_bitcoin" ]; then
    echo "  1. Build Bitcoin Core:"
    echo "     cd $CORE_PATH"
    echo "     ./autogen.sh && ./configure && make bench_bitcoin"
    echo ""
fi
echo "  2. Run benchmarks:"
echo "     ./run-benchmarks.sh fair"
echo ""

